# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def shared_pods
  # Pods for QMA
  pod 'Moya/RxSwift', '10.0.1'
  pod 'Moya-ObjectMapper/RxSwift', '2.5'
  pod 'ObjectMapper', '3.0.0'
  pod 'PopupDialog', '0.6.2'
  pod 'RxSwift', '4.0.0'
  pod 'RxCocoa', '4.0.0'
  pod 'KTCenterFlowLayout', '1.3.1'
  pod 'RxRealm'
  pod 'RSLoadingView'
  pod 'DeviceKit', '1.5.0'
  pod 'IHKeyboardAvoiding'
  
  # Pods for UPNP
  pod 'CocoaAsyncSocket'
  pod 'AFNetworking', '~> 3.0'
  pod 'Ono'
  pod 'GCDWebServer', '~> 3.0'
  
  # Pods for Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
end

target 'QMA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # call cocoapods
  shared_pods
  
  target 'QMATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QMAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'QMA_T11' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # call cocoapods
  shared_pods
end

target 'QMA_P01' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  
  # call cocoapods
  shared_pods
end